(define (average x y)
  (/ (+ x y) 2)
)

(define (sqrt n)
  (define (good-enough? guess)
	(< (abs (- (square guess) n)) 0.001)  		
  )
  (define (improve guess)
    (average guess (/ n guess))
  )
  (define (sqrt-iter guess)
    (if (good-enough? guess)
        guess
        (sqrt-iter (improve guess))
    )
  )
  (sqrt-iter 1.0)
)